# 🕵️‍♂️ Phase 0: Pre-Cleaning Data Analysis

This notebook performs a quick "health check" on the raw CSV datasets before the ETL pipeline.

**Goals:**
1.  Detect missing values and data quality issues on the ENTIRE dataset (optional chunked processing).
2.  Infer correct data types (int8/16/32 vs int64) for memory optimization.
3.  Identify columns to drop and verify string content.
4.  Identify almost-empty rows (irrelevant data).

In [1]:
%load_ext autoreload
%autoreload 2

import sys
import os
from pathlib import Path

# 🔧 Ensure project root is in path
current_dir = Path(os.getcwd())
solution_dir = current_dir.parent
if str(solution_dir.parent) not in sys.path:
    sys.path.append(str(solution_dir.parent))

from solution.src.data import RAW_FILES, get_raw_path
from nb_00_pre_cleaning_analysis import analyze_file

## 🚀 Run Analysis on Project Datasets

In [2]:
# Analyze each specific dataset defined for the project
print(f"Starting analysis for {len(RAW_FILES)} datasets...\n")

for name in RAW_FILES.keys():
    try:
        path = get_raw_path(name)
        analyze_file(str(path))
        print("=" * 40)
    except Exception as e:
        print(f"[ERROR] Failed to analyze {name} ({path}): {e}")

Starting analysis for 15 datasets...

  [DONE] Finished processing 28,955 rows in 0.45s using Pyarrow (Fast).
Total Rows: 28955

Primary Key Validation:
   [OK] 'mal_id': Unique (Candidate for PK)

MISSING VALUES ANALYSIS
[WARN] Missing Values Detected:

       Column  Missing Count  Percentage
6        year          22689   78.359523
3    end_date          17688   61.087895
0       score          10073   34.788465
1   scored_by          10073   34.788465
4        rank           6958   24.030392
2  start_date            851    2.939043
5    episodes            680    2.348472

[OK] No 'almost-empty' rows found

[INFO] Current Data Types:

                              Dtype
Column
mal_id                        int64
title                        object
title_japanese               object
url                          object
image_url                    object
type                         object
status                       object
score                       float64
scored_by                   float64
start_date       datetime64[s, UTC]
end_date         datetime64[s, UTC]
synopsis                     object
rank                        float64
popularity                    int64
members                       int64
favorites                     int64
genres                       object
studios                      object
themes                       object
demographics                 object
source                       object
rating                       object
episodes                    float64
season                       object
year                        float64
producers                    object
explicit_genres              object
licensors                    object
streaming                    object

----------------------------------------

[INFO] Optimization Recommendations:
   [INFO] Content Check 'title': ['-Socket-', '......', '.hack//G.U. Returner', '.hack//G.U. Trilogy', '.hack//G.U. Trilogy: Parody Mode']
   [INFO] Content Check 'title_japanese': ['-socket-', '......', '.HACK//G.U. RETURNER', '.hack//G.U. Trilogy', '.hack//G.U. Trilogy']
   [INFO] Content Check 'url': ['https://myanimelist.net/anime/59356/-Socket-', 'https://myanimelist.net/anime/56036/-', 'https://myanimelist.net/anime/2928/hack__GU_Returner', 'https://myanimelist.net/anime/3269/hack__GU_Trilogy', 'https://myanimelist.net/anime/4469/hack__GU_Trilogy__Parody_Mode']
   [INFO] Content Check 'image_url': ['https://cdn.myanimelist.net/images/anime/1043/144360.jpg', 'https://cdn.myanimelist.net/images/anime/1057/137264.jpg', 'https://cdn.myanimelist.net/images/anime/1798/115989.jpg', 'https://cdn.myanimelist.net/images/anime/1566/151023.jpg', 'https://cdn.myanimelist.net/images/anime/10/8661.jpg']
   [INFO] Content Check 'type': ['Movie', 'Music', 'OVA', 'Movie', 'Special']
   [INFO] Content Check 'status': ['Finished Airing', 'Finished Airing', 'Finished Airing', 'Finished Airing', 'Finished Airing']
   [INFO] Content Check 'synopsis': ['A girl with a cord growing out of her back wanders around hungry and searching for electricity.\n\n(Source: YouTube, translated)', 'Music video directed by obmolot for the song ...... by x0o0x_.', 'The characters from previous .hack//G.U. Games and .hack//Roots receive an email from Ovan. He is requesting them to go to Hidden Forbidden Festival where is set up a mysterious summer festival. There they find an AIDA Chim Chim who wishes to peacefully co-exist with the other players of The World. It then transforms into the word "Returner", so they assume it to mean that Ovan will return to The World.\n\n(Source: ANN)', 'Based on the CyberConnect2 HIT GAME, now will be released in a CG Movie!\n\nThe Movie will be placed in the storyline of each .hack//G.U. games trilogy. The story follows Haseo, a player in the online MMORPG called The World:R2 at first depicted as a PKK (Player Killer Killer) known as the "Terror of Death", a former member of the disbanded Twilight Brigade guild. Haseo encounters Azure Kite (believing him to be Tri-Edge and blaming him for what happened to Shino) but is hopelessly outmatched. Azure Kite easily defeats Haseo and Data Drains him, reducing his level from 133 to 1 and leaving him without any items, weapons, or member addresses. He is left with a mystery on his hands as to the nature of the Data Drain and why Azure Kite is in possession of such a skill.\n\nEventually Haseo gains the "Avatar" of Skeith. Acquiring the ability to call Skeith and wield his abilities, such as Data Drain. With Skeith as his strength, Haseo begins the quest for a way to save Shino.\n\nHe is seen seeking out a PK (Player Killer) known as Tri-Edge, whose victims supposedly are unable to return to The World after he PKs them. Haseo\'s friend, Shino, was attacked six months prior to the events of the game by Tri-Edge, and the player herself, Shino Nanao, was left in a coma.\n\n(Source: AniDB)', 'A special bonus Parody Mode added to the extras of the .hack//G.U. Trilogy \n\n(Source: AniDB)']
   [INFO] Content Check 'genres': ["['Comedy']", "['Horror', 'Supernatural']", "['Adventure', 'Drama', 'Fantasy']", "['Action', 'Fantasy']", "['Comedy', 'Fantasy', 'Sci-Fi']"]
   [INFO] Content Check 'studios': ['[]', "['Flat Studio']", "['Bee Train']", "['CyberConnect2']", '[]']
   [INFO] Content Check 'themes': ['[]', "['Music']", "['Video Game']", "['Video Game']", "['Parody', 'Video Game']"]
   [INFO] Content Check 'demographics': ['[]', '[]', '[]', '[]', '[]']
   [INFO] Content Check 'source': ['Original', 'Original', 'Game', 'Game', 'Game']
   [INFO] Content Check 'rating': ['G - All Ages', 'PG-13 - Teens 13 or older', 'PG-13 - Teens 13 or older', 'PG-13 - Teens 13 or older', 'PG-13 - Teens 13 or older']
   [INFO] Content Check 'season': ['', '', '', '', '']
   [INFO] Content Check 'producers': ["['Nagoya Zokei University']", '[]', "['Bandai Visual', 'CyberConnect2']", "['Bandai Visual']", "['Bandai Visual']"]
   [INFO] Content Check 'explicit_genres': ['[]', '[]', '[]', '[]', '[]']
   [INFO] Content Check 'licensors': ['[]', '[]', '[]', "['Funimation', 'Bandai Entertainment']", '[]']
   [INFO] Content Check 'streaming': ['[]', '[]', '[]', '[]', '[]']

,Column,Current,Recommended,Reason
0,mal_id,int64,int32,"Range [1, 62590]"
1,type,object,category,Low Cardinality (10 unique)
2,status,object,category,Low Cardinality (3 unique)
3,score,float64,float16,"Range [1.89, 9.29]"
4,scored_by,float64,float32,"Range [101, 2.9797e+06]"
5,start_date,"datetime64[s, UTC]",datetime,ISO-8601 Date Format Detected
6,end_date,"datetime64[s, UTC]",datetime,ISO-8601 Date Format Detected
7,rank,float64,float16,"Range [1, 22020]"
8,popularity,int64,int16,"Range [1, 28999]"
9,members,int64,int32,"Range [23, 4230312]"
10,favorites,int64,int32,"Range [0, 243358]"
11,genres,object,category,Low Cardinality (931 unique)
12,studios,object,category,Low Cardinality (1910 unique)
13,themes,object,category,Low Cardinality (1044 unique)
14,demographics,object,category,Low Cardinality (9 unique)
15,source,object,category,Low Cardinality (17 unique)
16,rating,object,category,Low Cardinality (7 unique)
17,episodes,float64,float16,"Range [1, 3000]"
18,season,object,category,Low Cardinality (5 unique)
19,year,float64,float16,"Range [1961, 2026]"
20,producers,object,category,Low Cardinality (5306 unique)
21,explicit_genres,object,category,Low Cardinality (1 unique)
22,licensors,object,category,Low Cardinality (304 unique)
23,streaming,object,category,Low Cardinality (434 unique)

========================================
  [DONE] Finished processing 28,955 rows in 0.27s using Pyarrow (Fast).
Total Rows: 28955

Primary Key Validation:
   [OK] 'mal_id': Unique (Candidate for PK)

MISSING VALUES ANALYSIS
[WARN] Missing Values Detected:

                 Column  Missing Count  Percentage
0         score_1_votes            430    1.485063
1    score_1_percentage            430    1.485063
2         score_2_votes            430    1.485063
3    score_2_percentage            430    1.485063
4         score_3_votes            430    1.485063
5    score_3_percentage            430    1.485063
6         score_4_votes            430    1.485063
7    score_4_percentage            430    1.485063
8         score_5_votes            430    1.485063
9    score_5_percentage            430    1.485063
10        score_6_votes            430    1.485063
11   score_6_percentage            430    1.485063
12        score_7_votes            430    1.485063
13   score_7_percentage            430    1.485063
14        score_8_votes            430    1.485063
15   score_8_percentage            430    1.485063
16        score_9_votes            430    1.485063
17   score_9_percentage            430    1.485063
18       score_10_votes            430    1.485063
19  score_10_percentage            430    1.485063

[OK] No 'almost-empty' rows found

[INFO] Current Data Types:

                       Dtype
Column
mal_id                 int64
watching               int64
completed              int64
on_hold                int64
dropped                int64
plan_to_watch          int64
total                  int64
score_1_votes        float64
score_1_percentage   float64
score_2_votes        float64
score_2_percentage   float64
score_3_votes        float64
score_3_percentage   float64
score_4_votes        float64
score_4_percentage   float64
score_5_votes        float64
score_5_percentage   float64
score_6_votes        float64
score_6_percentage   float64
score_7_votes        float64
score_7_percentage   float64
score_8_votes        float64
score_8_percentage   float64
score_9_votes        float64
score_9_percentage   float64
score_10_votes       float64
score_10_percentage  float64

----------------------------------------

[INFO] Optimization Recommendations:

                 Column  Current Recommended                 Reason
0                mal_id    int64       int32       Range [1, 62590]
1              watching    int64       int32     Range [0, 1838015]
2             completed    int64       int32     Range [0, 3716436]
3               on_hold    int64       int32      Range [0, 308583]
4               dropped    int64       int32      Range [0, 237819]
5         plan_to_watch    int64       int32      Range [2, 687110]
6                 total    int64       int32    Range [23, 4230824]
7         score_1_votes  float64     float16       Range [0, 50279]
8    score_1_percentage  float64     float16         Range [0, 100]
9         score_2_votes  float64     float16       Range [0, 36397]
10   score_2_percentage  float64     float16         Range [0, 100]
11        score_3_votes  float64     float16       Range [0, 59478]
12   score_3_percentage  float64     float16        Range [0, 52.4]
13        score_4_votes  float64     float32  Range [0, 1.1296e+05]
14   score_4_percentage  float64     float16         Range [0, 100]
15        score_5_votes  float64     float32  Range [0, 1.7963e+05]
16   score_5_percentage  float64     float16         Range [0, 100]
17        score_6_votes  float64     float32  Range [0, 2.8197e+05]
18   score_6_percentage  float64     float16         Range [0, 100]
19        score_7_votes  float64     float32  Range [0, 5.1496e+05]
20   score_7_percentage  float64     float16         Range [0, 100]
21        score_8_votes  float64     float32  Range [0, 7.5664e+05]
22   score_8_percentage  float64     float16         Range [0, 100]
23        score_9_votes  float64     float32  Range [0, 8.7255e+05]
24   score_9_percentage  float64     float16         Range [0, 100]
25       score_10_votes  float64     float32  Range [0, 1.0905e+06]
26  score_10_percentage  float64     float16         Range [0, 100]

========================================
  [DONE] Finished processing 337,155 rows in 1.01s using Pyarrow (Fast).
Total Rows: 337155

Primary Key Validation:
   [OK] 'username': Unique (Candidate for PK)

MISSING VALUES ANALYSIS
[OK] No Missing Values Found

[OK] No 'almost-empty' rows found

[INFO] Current Data Types:

                Dtype
Column
username       object
gender         object
birthday       object
location       object
joined         object
watching       object
completed      object
on_hold        object
dropped        object
plan_to_watch  object

----------------------------------------

[INFO] Optimization Recommendations:
   [INFO] Content Check 'username': ['ishikawas', 'CKK2', '--------788', 'potatoaris', 'Rinrintan']
   [INFO] Content Check 'gender': ['', '', 'Female', '', '']
   [INFO] Content Check 'birthday': ['', '', '', '', '']
   [INFO] Content Check 'location': ['South Korea', 'United States', 'Mexico', 'Spain', 'Japan']
   [INFO] Content Check 'joined': ['', 'Dec 1, 2018', 'Oct 4, 2022', 'Oct 2, 2018', 'May 12, 2019']
   [INFO] Content Check 'watching': ['', '3', '1', '5', '20']
   [INFO] Content Check 'completed': ['', '182', '64', '1', '311']
   [INFO] Content Check 'on_hold': ['', '15', '0', '0', '40']
   [INFO] Content Check 'dropped': ['', '0', '0', '0', '16']
   [INFO] Content Check 'plan_to_watch': ['', '405', '1', '4', '34']

          Column Current Recommended                         Reason
0         gender  object    category     Low Cardinality (4 unique)
1       location  object    category    Low Cardinality (22 unique)
2         joined  object    category  Low Cardinality (6803 unique)
3       watching  object    category   Low Cardinality (943 unique)
4      completed  object    category  Low Cardinality (3381 unique)
5        on_hold  object    category   Low Cardinality (739 unique)
6        dropped  object    category   Low Cardinality (901 unique)
7  plan_to_watch  object    category  Low Cardinality (2539 unique)

========================================
[WARN] Memory check failed: [WinError 2] Impossibile trovare il file specificato: 'C:\\Users\\user\\OneDrive\\Desktop\\IUM\\Ciravegna\\unito-hci-data-analysis-25-26\\data\\raw\\reviews.csv'. Proceeding blindly.
  [INFO] Pyarrow engine failed: [WinError 2] Failed to open local file 'C:/Users/user/OneDrive/Desktop/IUM/Ciravegna/unito-hci-data-analysis-25-26/data/raw/reviews.csv'. Detail: [Windows error 2] Impossibile trovare il file specificato.

  -> Falling back to chunked 'c' engine...
[ERROR] reading file: [Errno 2] No such file or directory: 'C:\\Users\\user\\OneDrive\\Desktop\\IUM\\Ciravegna\\unito-hci-data-analysis-25-26\\data\\raw\\reviews.csv'
[WARN] File appears to be empty or unreadable.
========================================
  [DONE] Finished processing 105,249 rows in 0.08s using Pyarrow (Fast).
Total Rows: 105249

Primary Key Validation:
   [FAIL] 'mal_id': Duplicates found (Not a PK)
   [FAIL] 'recommendation_mal_id': Duplicates found (Not a PK)
   [WARN] No obvious unique Primary Key found.

MISSING VALUES ANALYSIS
[OK] No Missing Values Found

[OK] No 'almost-empty' rows found

[INFO] Current Data Types:

                       Dtype
Column
mal_id                 int64
recommendation_mal_id  int64

----------------------------------------

[INFO] Optimization Recommendations:

                  Column Current Recommended            Reason
0                 mal_id   int64       int32  Range [1, 62417]
1  recommendation_mal_id   int64       int32  Range [1, 62417]

========================================
  [DONE] Finished processing 209,963 rows in 1.00s using Pyarrow (Fast).
Total Rows: 209963

Primary Key Validation:
   [FAIL] 'character_mal_id': Duplicates found (Not a PK)
   [WARN] No obvious unique Primary Key found.

MISSING VALUES ANALYSIS
[WARN] Missing Values Detected:

             Column  Missing Count  Percentage
0  character_mal_id              2    0.000953
1         favorites              2    0.000953

[OK] No 'almost-empty' rows found

[INFO] Current Data Types:

                    Dtype
Column
character_mal_id  float64
url                object
name               object
name_kanji         object
image              object
favorites         float64
about              object

----------------------------------------

[INFO] Optimization Recommendations:
   [INFO] Content Check 'url': ['https://myanimelist.net/character/280386/Envi_Mel_Champagne', 'https://myanimelist.net/character/280354/Eleven', 'https://myanimelist.net/character/280353/Stud', 'https://myanimelist.net/character/280352/Judge', 'https://myanimelist.net/character/280339/Eiji_Kurokawa']
   [INFO] Content Check 'name': ['Envi Mel Champagne', 'Eleven', 'Stud', 'Judge', 'Eiji Kurokawa']
   [INFO] Content Check 'name_kanji': ['エンヴィ・メル・シャンパーニュ', 'イレヴン', 'スタッド', 'ジャッジ', '黒川 英治']
   [INFO] Content Check 'image': ['https://cdn.myanimelist.net/images/characters/7/607317.jpg', 'https://cdn.myanimelist.net/images/characters/5/607261.jpg', 'https://cdn.myanimelist.net/images/characters/10/607260.jpg', 'https://cdn.myanimelist.net/images/characters/5/607259.jpg', 'https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png']
   [INFO] Content Check 'about': ['', '', '', '', '']

             Column  Current Recommended                 Reason
0  character_mal_id  float64     float32  Range [1, 2.8228e+05]
1         favorites  float64     float32  Range [0, 1.7563e+05]

========================================
  [DONE] Finished processing 4,178,747 rows in 2.88s using Pyarrow (Fast).
Total Rows: 4178747

Primary Key Validation:
   [FAIL] 'username': Duplicates found (Not a PK)
   [FAIL] 'id': Duplicates found (Not a PK)
   [WARN] No obvious unique Primary Key found.

MISSING VALUES ANALYSIS
[OK] No Missing Values Found

[OK] No 'almost-empty' rows found

[INFO] Current Data Types:

           Dtype
Column
username  object
fav_type  object
id         int64

----------------------------------------

[INFO] Optimization Recommendations:
   [INFO] Content Check 'username': ['ishikawas', 'ishikawas', 'ishikawas', 'ishikawas', 'ishikawas']
   [INFO] Content Check 'fav_type': ['anime', 'anime', 'anime', 'anime', 'anime']

     Column Current Recommended                      Reason
0  fav_type  object    category  Low Cardinality (4 unique)
1        id   int64       int32           Range [1, 281988]

========================================
  [INFO] File size (4295.9 MB) too large for safer Pyarrow load with 3597.5 MB RAM available.
  -> Using chunked stream...
  [DONE] Finished processing 124,298,357 rows in 87.50s using Standard C-Engine (Chunked).
Total Rows: 124298357

Primary Key Validation:
   [FAIL] 'username': Duplicates found (Not a PK)
   [FAIL] 'anime_id': Duplicates found (Not a PK)
   [WARN] No obvious unique Primary Key found.

MISSING VALUES ANALYSIS
[WARN] Missing Values Detected:

          Column  Missing Count  Percentage
1  is_rewatching        3797321    3.055005
0       username              7    0.000006

[OK] No 'almost-empty' rows found

[INFO] Current Data Types:

                        Dtype
Column
username               object
anime_id                int64
status                 object
score                   int64
is_rewatching         float64
num_watched_episodes    int64

----------------------------------------

[INFO] Optimization Recommendations:
   [INFO] Content Check 'username': ['--------788', '--------788', '--------788', '--------788', '--------788']
   [INFO] Content Check 'status': ['watching', 'completed', 'completed', 'completed', 'completed']

                 Column  Current Recommended                      Reason
0              anime_id    int64       int32            Range [1, 62893]
1                status   object    category  Low Cardinality (6 unique)
2                 score    int64        int8               Range [0, 10]
3         is_rewatching  float64     float16                Range [0, 1]
4  num_watched_episodes    int64       int32            Range [0, 65535]

========================================
  [DONE] Finished processing 37,080 rows in 0.05s using Pyarrow (Fast).
Total Rows: 37080

Primary Key Validation:
   [FAIL] 'character_mal_id': Duplicates found (Not a PK)
   [WARN] No obvious unique Primary Key found.

MISSING VALUES ANALYSIS
[OK] No Missing Values Found

[OK] No 'almost-empty' rows found

[INFO] Current Data Types:

                   Dtype
Column
character_mal_id   int64
nickname          object

----------------------------------------

[INFO] Optimization Recommendations:
   [INFO] Content Check 'nickname': ['Hikaruko', 'Hinacchi', 'Bertha Willis', 'Jimmy', 'Full Body Red Square']

             Column Current Recommended             Reason
0  character_mal_id   int64       int32  Range [3, 282255]

========================================
  [DONE] Finished processing 236,816 rows in 0.32s using Pyarrow (Fast).
Total Rows: 236816

Primary Key Validation:
   [FAIL] 'anime_mal_id': Duplicates found (Not a PK)
   [FAIL] 'character_mal_id': Duplicates found (Not a PK)
   [WARN] No obvious unique Primary Key found.

MISSING VALUES ANALYSIS
[OK] No Missing Values Found

[OK] No 'almost-empty' rows found

[INFO] Current Data Types:

                   Dtype
Column
anime_mal_id       int64
character_mal_id   int64
character_name    object
role              object

----------------------------------------

[INFO] Optimization Recommendations:
   [INFO] Content Check 'character_name': ['Atoli', 'Haseo', 'Ovan', 'Shino', 'Aina']
   [INFO] Content Check 'role': ['Main', 'Main', 'Main', 'Main', 'Supporting']

             Column Current Recommended                      Reason
0      anime_mal_id   int64       int32            Range [1, 62584]
1  character_mal_id   int64       int32           Range [1, 282284]
2              role  object    category  Low Cardinality (2 unique)

========================================
[WARN] Memory check failed: [WinError 2] Impossibile trovare il file specificato: 'C:\\Users\\user\\OneDrive\\Desktop\\IUM\\Ciravegna\\unito-hci-data-analysis-25-26\\data\\raw\\person.csv'. Proceeding blindly.
  [INFO] Pyarrow engine failed: [WinError 2] Failed to open local file 'C:/Users/user/OneDrive/Desktop/IUM/Ciravegna/unito-hci-data-analysis-25-26/data/raw/person.csv'. Detail: [Windows error 2] Impossibile trovare il file specificato.

  -> Falling back to chunked 'c' engine...
[ERROR] reading file: [Errno 2] No such file or directory: 'C:\\Users\\user\\OneDrive\\Desktop\\IUM\\Ciravegna\\unito-hci-data-analysis-25-26\\data\\raw\\person.csv'
[WARN] File appears to be empty or unreadable.
========================================
  [DONE] Finished processing 76,699 rows in 0.42s using Pyarrow (Fast).
Total Rows: 76699

Primary Key Validation:
   [FAIL] 'person_mal_id': Duplicates found (Not a PK)
   [WARN] No obvious unique Primary Key found.

MISSING VALUES ANALYSIS
[WARN] Missing Values Detected:

     Column  Missing Count  Percentage
0  birthday          59461   77.525131

[OK] No 'almost-empty' rows found

[INFO] Current Data Types:

                                Dtype
Column
person_mal_id                   int64
url                            object
website_url                    object
image_url                      object
name                           object
given_name                     object
family_name                    object
birthday           datetime64[s, UTC]
favorites                       int64
relevant_location              object

----------------------------------------

[INFO] Optimization Recommendations:
   [INFO] Content Check 'url': ['https://myanimelist.net/people/1/Tomokazu_Seki', 'https://myanimelist.net/people/2/Tomokazu_Sugita', 'https://myanimelist.net/people/3/Satsuki_Yukino', 'https://myanimelist.net/people/4/Aya_Hirano', 'https://myanimelist.net/people/5/Kenichi_Suzumura']
   [INFO] Content Check 'website_url': ['', 'https://agrs.co.jp/', '', 'http://ayahirano.jp/', 'https://intention-k.com']
   [INFO] Content Check 'image_url': ['https://cdn.myanimelist.net/images/voiceactors/1/85360.jpg', 'https://cdn.myanimelist.net/images/voiceactors/1/81054.jpg', 'https://cdn.myanimelist.net/images/voiceactors/1/75881.jpg', 'https://cdn.myanimelist.net/images/voiceactors/3/78608.jpg', 'https://cdn.myanimelist.net/images/voiceactors/1/79443.jpg']
   [INFO] Content Check 'name': ['Tomokazu Seki', 'Tomokazu Sugita', 'Satsuki Yukino', 'Aya Hirano', 'Kenichi Suzumura']
   [INFO] Content Check 'given_name': ['智一', '智和', 'さつき', '綾', '健一']
   [INFO] Content Check 'family_name': ['関', '杉田', 'ゆきの', '平野', '鈴村']
   [INFO] Content Check 'relevant_location': ['Berlin, Germany', 'Los Angeles, USA', 'Madrid, Spain', 'Paris, France', 'Osaka, Japan']

,Column,Current,Recommended,Reason
0,person_mal_id,int64,int32,"Range [1, 90015]"
1,birthday,"datetime64[s, UTC]",datetime,ISO-8601 Date Format Detected
2,favorites,int64,int32,"Range [0, 108157]"
3,relevant_location,object,category,Low Cardinality (20 unique)

========================================
  [DONE] Finished processing 458,091 rows in 0.55s using Pyarrow (Fast).
Total Rows: 458091

Primary Key Validation:
   [FAIL] 'person_mal_id': Duplicates found (Not a PK)
   [FAIL] 'anime_mal_id': Duplicates found (Not a PK)
   [WARN] No obvious unique Primary Key found.

MISSING VALUES ANALYSIS
[OK] No Missing Values Found

[OK] No 'almost-empty' rows found

[INFO] Current Data Types:

                Dtype
Column
person_mal_id   int64
position       object
anime_mal_id    int64

----------------------------------------

[INFO] Optimization Recommendations:
   [INFO] Content Check 'position': ['Theme Song Performance', 'Inserted Song Performance', 'Theme Song Performance (OP)', 'Theme Song Performance', 'Theme Song Performance (ED)']

          Column Current Recommended            Reason
0  person_mal_id   int64       int32  Range [1, 89965]
1   anime_mal_id   int64       int32  Range [1, 62637]

========================================
  [DONE] Finished processing 489,516 rows in 0.64s using Pyarrow (Fast).
Total Rows: 489516

Primary Key Validation:
   [FAIL] 'person_mal_id': Duplicates found (Not a PK)
   [FAIL] 'anime_mal_id': Duplicates found (Not a PK)
   [FAIL] 'character_mal_id': Duplicates found (Not a PK)
   [WARN] No obvious unique Primary Key found.

MISSING VALUES ANALYSIS
[OK] No Missing Values Found

[OK] No 'almost-empty' rows found

[INFO] Current Data Types:

                   Dtype
Column
person_mal_id      int64
role              object
anime_mal_id       int64
character_mal_id   int64
language          object

----------------------------------------

[INFO] Optimization Recommendations:
   [INFO] Content Check 'role': ['Main', 'Supporting', 'Supporting', 'Supporting', 'Supporting']
   [INFO] Content Check 'language': ['Japanese', 'Japanese', 'Japanese', 'Japanese', 'Japanese']

             Column Current Recommended                       Reason
0     person_mal_id   int64       int32             Range [1, 89952]
1              role  object    category   Low Cardinality (2 unique)
2      anime_mal_id   int64       int32             Range [1, 62584]
3  character_mal_id   int64       int32            Range [1, 280366]
4          language  object    category  Low Cardinality (11 unique)

========================================
  [DONE] Finished processing 20,465 rows in 0.06s using Pyarrow (Fast).
Total Rows: 20465

Primary Key Validation:
   [FAIL] 'person_mal_id': Duplicates found (Not a PK)
   [WARN] No obvious unique Primary Key found.

MISSING VALUES ANALYSIS
[OK] No Missing Values Found

[OK] No 'almost-empty' rows found

[INFO] Current Data Types:

                Dtype
Column
person_mal_id   int64
alt_name       object

----------------------------------------

[INFO] Optimization Recommendations:
   [INFO] Content Check 'alt_name': ['Seki Mondoya', '門戸 開', 'Monto Hiraku', '雪野五月', 'Kevin Hatcher']

          Column Current Recommended            Reason
0  person_mal_id   int64       int32  Range [1, 89842]

========================================